#
# np-dl-assign-2
# continuous integration (ci) pipeline (p2)
#

name: "CI Pipeline - Text Generation Model (p2)"
on:
  push:
    paths:
    - "notebooks/Assignment_2_p2.ipynb"
    - "pipelines/*.yaml"
jobs:
  argo-train-eval-model-p2:
    runs-on: ubuntu-20.04
    name: "Train evaluate Text Generation Model (p2) on Argo"
    env:
      ARGO_SERVER: argo.mrzzy.co:443
      ARGO_HTTP1: true
      ARGO_SECURE: true
      ARGO_NAMESPACE: argo
      ARGO_TOKEN: "Bearer ${{ secrets.ARGO_TOKEN }}"
      KUBECONFIG: /dev/null
    steps:
      - uses: actions/checkout@v2
      - name: "Install argo CLI"
        run: |
          # install argo cli with steps stolen from argo quickstart
          # https://github.com/argoproj/argo/releases?after=v2.12.6
          curl -sLO https://github.com/argoproj/argo/releases/download/v2.12.6/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod a+x argo-linux-amd64
          mv ./argo-linux-amd64 ./argo
      - name: "Trigger 'train-eval-model' Workflow on Argo"
        run: |
          # use https with http1 (non-grpc) to submit workflow
          ./argo submit pipelines/dl.yaml \
            -p notebook-name=Assignment_2_p2 -p mlflow-experiment=np-dl-2-p2-textgen

